import { AppContext } from '../Integration/context'
import React,{useContext , useState} from 'react'
import Head from 'next/head';


const Page = () => {
const {StoreStringNdUint,readString , contract} = useContext(AppContext); // use as usual precautions for data submitted , I will just use useStates
  const [string , setString]=useState("");
  const [address , setAddress]=useState("");
  const [uint , setUint]=useState();
  console.log(contract);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
            <h3>NO NEED TO TYPE IT IS HARDCODED AS I COULD NOT FIGURE OUT HOW TO PASS THE DATA PROPERLY REFER TO .Integration/context.js </h3>
        <input
        type="string"
        placeholder='string data'
        onChange={(e)=> setString(e.target.value)}
        />
        <input
        type="number"
        placeholder='Uint data '
        onChange={(e)=> setUint(e.target.value)}
        />

        <button onClick={()=>StoreStringNdUint(string , uint)}>
          Save To Chain
        </button>         
        </div>

        <div>
            <button onClick={()=> readString(address)}>  {/* THIS NEEDS PROPER SET UP to Show the values returned, the smart contract functions returns data of type string :'(  */}
                SHOW SAVED
            </button>
            <input type="text"
            placeholder='type address of user to check'
            onChange={(e)=> setAddress(e.target.value)}
            />
        </div>
      </main>
    </>
  )
}

export default Page